# 1. 필요한 라이브러리

In [120]:
import pandas as pd
import numpy as np
import time
from datetime import datetime
from datetime import timedelta

# 2. 아동,행위자 데이터 불러오기

In [6]:
Child = pd.read_csv("C:\\Users\\KDJ\\Desktop\\SSIS\\Child_new4.csv", encoding='cp949')

C:\Users\KDJ\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3063: DtypeWarning: Columns (4,21,22,25,29,31,44,49) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [13]:
df1 = Child
df1

,개별사건번호,피해아동대상자,학대행위자대상,아동_성별,아동_연령대,아동_내국인여부,아동_최종학력,아동_직업유형,아동_거주상태,아동_친권자유형,...,아조_원가정보호,아조_가정복귀,행조_아동과의분리,행조_만나지못함,행조_모니터링,행조_고소고발사건처,행조_사건처리만나지,New_Abuse_Count,New_재학대혐의여부,New_Call_Count
0,0102010220141200510001,CASRCP20121010398,CASRCP20121020314,M,NaN,내국인,NaN,NaN,자택,양부모,...,0,0,0,0,0,0,0,NaN,NaN,0.0
1,0804080420141200220001,CASRCP20150110545,CASRCP20150120502,M,NaN,내국인,NaN,NaN,기타,친부모,...,1,0,0,0,1,0,0,0.0,N,0.0
2,0402040220141200170001,CASRCP20141211229,CASRCP20141221114,M,NaN,내국인,NaN,NaN,NaN,친부,...,0,0,0,0,0,0,0,NaN,NaN,0.0
3,0402040220141200160001,CASRCP20141211178,CASRCP20141221114,F,NaN,내국인,NaN,NaN,NaN,친부,...,0,0,0,0,0,0,0,NaN,NaN,0.0
4,0106080420141200200001,CASRCP20141211459,CASRCP20141221403,F,NaN,내국인,NaN,NaN,보증금(전세)+월세,친부모,...,0,0,0,0,0,0,0,NaN,NaN,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
122030,5801580120180165450001,CASRCP20180100595,CASRCP20180100597,M,1~3세,내국인,NaN,어린이집,NaN,친모,...,1,0,0,0,1,0,0,0.0,N,0.0
122031,5115511520180165080001,CASRCP20180100289,CASRCP20180100290,F,13~15세,내국인,재학중,초등학교,NaN,친모,...,1,0,0,0,1,0,0,0.0,N,0.0
122032,6404640420180167080001,CASRCP20180102065,CASRCP20180102067,F,NaN,NaN,NaN,NaN,NaN,친부모,...,0,0,0,0,0,0,0,NaN,NaN,0.0
122033,5715571520180166300001,CASRCP20180101264,CASRCP20180101266,M,1~3세,내국인,재학중,어린이집,NaN,친부모,...,0,0,0,0,0,0,0,NaN,NaN,0.0
122034,5715571520180166300002,CASRCP20180101267,CASRCP20180101266,F,4~6세,내국인,재학중,어린이집,전세,친부모,...,0,0,0,0,0,0,0,NaN,NaN,0.0

In [16]:
df1.columns

Index(['개별사건번호', '피해아동대상자', '학대행위자대상', '아동_성별', '아동_연령대', '아동_내국인여부',
       '아동_최종학력', '아동_직업유형', '아동_거주상태', '아동_친권자유형', '아동_가족유형', '아동_다문화가족',
       '아동_가구소득구분코', '아동_기초생활수급유', '아동_주요병력', '아동_보호조치유형', '신고_접수경로구분코',
       '신고_접수일시', '신고_신고자유형구분', '신고_통보경찰소속기', '신고_집단시설내사건', '신고_재신고여부_1',
       '신고_재신고유형', '신고_재신고이전접수', '신고_접수유형', '신고_관할지구대', '신고_신고접수구분',
       '신고_접수자소속기관', '신고_관할지역ID', '신고_관련키워드', '신고_피해아동상태구', '신고_재신고센터ID',
       '신고_관할지역기관I', '신고_관리센터ID', '신대_행위자아동관계', '신대_아동동거여부', '신대_접수유형',
       '신대_재신고여부', '신대_재신고유형_1', '신대_재신고센터ID', '신대_재신고이전', '신대_통계거점',
       '신대_통계기관', '신대_통계관할지역', '조사_집단시설내사건', '조사_조사완료여부', '조사_관할지역ID_',
       '조사_관할지역기관I', '조사_위험_점수', '조사_위험_유형', '조대_재신고여부_1', '조대_재신고유형구분',
       '조대_재신고관리기관', '조대_재신고이전사건', '조대_동일신고여부', '조대_아동동거여부', '조대_특별관리유형',
       '판단_학대혐의여부', '판단_유형_신체', '판단_유형_정서', '판단_유형_성', '판단_유형_방임', '판단_유형_유기',
       '판단_학대발생빈도', '결과_조치결과일자', '신고_접수연도', '아조_분리조치', '아조_사망', '아조_원가정보호',
       '아조_가정복귀', '행조_아동과의분리', '행조_만나지못함', '행조_모니터링', '행조_고소고발사건처',
       '행조_사건처리만나지', 'New_Abuse_Count', 'New_재학대혐의여부', 'New_Call_Count'],
      dtype='object')

In [160]:
df2 = df1[['신고_접수일시','결과_조치결과일자']]
df3 = df2.dropna()

In [47]:
df3.index

Int64Index([     1,      7,      9,     14,     15,     18,     19,     21,
                24,     25,
            ...
            122020, 122021, 122022, 122023, 122024, 122027, 122028, 122029,
            122030, 122031],
           dtype='int64', length=87560)

In [87]:
df3
# df3['신고_접수일시'][1]

                    신고_접수일시   결과_조치결과일자
1       2014-12-31 21:30:00  20150818.0
7       2014-12-31 16:54:00  20160112.0
9       2014-12-31 16:31:00  20160107.0
14      2014-12-31 15:20:00  20151125.0
15      2014-12-31 13:46:00  20150302.0
...                     ...         ...
122027  2018-01-01 11:50:00  20180110.0
122028  2018-01-01 11:39:00  20180109.0
122029  2018-01-01 08:20:00  20180917.0
122030  2018-01-01 06:50:00  20180105.0
122031  2018-01-01 00:40:00  20180111.0

[87560 rows x 2 columns]

In [222]:
df3['New_조치걸린일수'] = 0
df3

C:\Users\KDJ\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

                    신고_접수일시   결과_조치결과일자  New_조치걸린일수
1       2014-12-31 21:30:00  20150818.0           0
7       2014-12-31 16:54:00  20160112.0           0
9       2014-12-31 16:31:00  20160107.0           0
14      2014-12-31 15:20:00  20151125.0           0
15      2014-12-31 13:46:00  20150302.0           0
...                     ...         ...         ...
122027  2018-01-01 11:50:00  20180110.0           0
122028  2018-01-01 11:39:00  20180109.0           0
122029  2018-01-01 08:20:00  20180917.0           0
122030  2018-01-01 06:50:00  20180105.0           0
122031  2018-01-01 00:40:00  20180111.0           0

[87560 rows x 3 columns]

for i in df3.index:
    t1 = str(int(df3['결과_조치결과일자'][i]))
    t1 = t1[:4]+'-'+t1[4:6]+'-'+t1[6:8]+' 23:59:59'
    t1 = datetime.strptime(t1,'%Y-%m-%d %H:%M:%S')
    t2 = datetime.strptime(df3['신고_접수일시'][i], '%Y-%m-%d %H:%M:%S')
    result = t1-t2
    df3['New_조치걸린시간'][i] = int(str(result).split('days')[0])

In [223]:
for i in df3.index:
    try:
        t1 = str(int(df3['결과_조치결과일자'][i])) # 조치일자 
        t1 = t1[:4]+'-'+t1[4:6]+'-'+t1[6:8]
        t1 = datetime.strptime(t1,'%Y-%m-%d')
        t2 = datetime.strptime(df3['신고_접수일시'][i], '%Y-%m-%d %H:%M:%S') # 접수일자
        result = t1-t2
        if(int(str(result).split('days')[0].split('day')[0])==-1): # 당일
            df3['New_조치걸린일수'][i] = 0
        elif(int(str(result).split('days')[0]) > 0): # 음수제외 일수 삽입
            df3['New_조치걸린일수'][i] = int(str(result).split('days')[0])
        else: # 음수일때 nan 삽입
            df3['New_조치걸린일수'][i]=np.nan 
    except ValueError:
        if(result<=timedelta(days=1)): # 다음날 조치
            df3['New_조치걸린일수'][i]=1
            continue
        df3['New_조치걸린일수'][i]=np.nan # 그외 에러일때 nan

C:\Users\KDJ\anaconda3\lib\site-packages\ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()
C:\Users\KDJ\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3331: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  exec(code_obj, self.user_global_ns, self.user_ns)
C:\Users\KDJ\anaconda3\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':
C:\Users\KDJ\anaconda3\lib\site-packages\ipykernel_launcher.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  app.launch_new_instance()
C:\Users\KDJ\anaconda3\lib\site-packages\ipykernel_launcher.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\KDJ\anaconda3\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)
C:\Users\KDJ\anaconda3\lib\site-packages\pandas\core\series.py:1024: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.loc[key] = value
C:\Users\KDJ\anaconda3\lib\site-packages\ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]

In [231]:
# sorted(df3['New_조치걸린일수'].value_counts().index)
df3['New_조치걸린일수'].value_counts()
# df3.isnull().sum()
# df3

0.0       5934
1.0       4546
2.0       2979
6.0       2825
5.0       2818
          ...
869.0        1
816.0        1
1100.0       1
938.0        1
880.0        1
Name: New_조치걸린일수, Length: 1089, dtype: int64

In [232]:
df1['New_조치걸린일수'] = np.nan
df1

,개별사건번호,피해아동대상자,학대행위자대상,아동_성별,아동_연령대,아동_내국인여부,아동_최종학력,아동_직업유형,아동_거주상태,아동_친권자유형,...,아조_가정복귀,행조_아동과의분리,행조_만나지못함,행조_모니터링,행조_고소고발사건처,행조_사건처리만나지,New_Abuse_Count,New_재학대혐의여부,New_Call_Count,New_조치걸린일수
0,0102010220141200510001,CASRCP20121010398,CASRCP20121020314,M,NaN,내국인,NaN,NaN,자택,양부모,...,0,0,0,0,0,0,NaN,NaN,0.0,NaN
1,0804080420141200220001,CASRCP20150110545,CASRCP20150120502,M,NaN,내국인,NaN,NaN,기타,친부모,...,0,0,0,1,0,0,0.0,N,0.0,NaN
2,0402040220141200170001,CASRCP20141211229,CASRCP20141221114,M,NaN,내국인,NaN,NaN,NaN,친부,...,0,0,0,0,0,0,NaN,NaN,0.0,NaN
3,0402040220141200160001,CASRCP20141211178,CASRCP20141221114,F,NaN,내국인,NaN,NaN,NaN,친부,...,0,0,0,0,0,0,NaN,NaN,0.0,NaN
4,0106080420141200200001,CASRCP20141211459,CASRCP20141221403,F,NaN,내국인,NaN,NaN,보증금(전세)+월세,친부모,...,0,0,0,0,0,0,NaN,NaN,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
122030,5801580120180165450001,CASRCP20180100595,CASRCP20180100597,M,1~3세,내국인,NaN,어린이집,NaN,친모,...,0,0,0,1,0,0,0.0,N,0.0,NaN
122031,5115511520180165080001,CASRCP20180100289,CASRCP20180100290,F,13~15세,내국인,재학중,초등학교,NaN,친모,...,0,0,0,1,0,0,0.0,N,0.0,NaN
122032,6404640420180167080001,CASRCP20180102065,CASRCP20180102067,F,NaN,NaN,NaN,NaN,NaN,친부모,...,0,0,0,0,0,0,NaN,NaN,0.0,NaN
122033,5715571520180166300001,CASRCP20180101264,CASRCP20180101266,M,1~3세,내국인,재학중,어린이집,NaN,친부모,...,0,0,0,0,0,0,NaN,NaN,0.0,NaN
122034,5715571520180166300002,CASRCP20180101267,CASRCP20180101266,F,4~6세,내국인,재학중,어린이집,전세,친부모,...,0,0,0,0,0,0,NaN,NaN,0.0,NaN

In [233]:
for i in df3.index:
    df1['New_조치걸린일수'][i] = df3['New_조치걸린일수'][i]

C:\Users\KDJ\anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [238]:
df1['New_조치걸린일수'].value_counts()

0.0       5934
1.0       4546
2.0       2979
6.0       2825
5.0       2818
          ...
869.0        1
816.0        1
1100.0       1
938.0        1
880.0        1
Name: New_조치걸린일수, Length: 1089, dtype: int64

In [237]:
df1['New_조치걸린일수'].isnull().sum()

37800

In [240]:
df1.to_csv('C:\\Users\\KDJ\\Desktop\\SSIS\\New_action_days.csv', encoding='cp949')